### ISSUE TITLE
Add ID  to Edit Author Slug

### ISSUE THREAD

**Issue by Sebaortiz** [thebrandonallen/edit-author-slug#15]
it is possible to add the user id to the slug?

Example:
http://example.com/ninja/master-ninja/ID

**Comment by thebrandonallen** [comment]
This is possible, but only if you write some custom code to achieve this.

You would need to append the the `/ID` to every author URL, and you would also need to intercept all requests so you could direct these new URLs to the correct author. WordPress won't handle this by default.

**Comment by Sebaortiz** [comment]
It sounds interesting, what is the way forward?

maybe in a new version could include that new functionality

**Comment by thebrandonallen** [comment]
This is beyond the scope of what I want the plugin to do. At this time, I will not be adding this functionality.
