### ISSUE TITLE
I want to know the reason for this error

### ISSUE THREAD

**Issue by tartan7** [thebrandonallen/edit-author-slug#20]
Hi

Warning:require(jncludes/classes/class-ba-edit-author-slug.php):failed to open stream:No such file or directory in XXXXXXXXXXXX /edit-author-slug.php on line 38

Fatal error:require():Failed opening required 'jncludes/classes/class-ba-edit-author-slug.php'(include_path',:xxxxxxxxxx') in XXXXXXXXXXXXXXXXXXX/edit-author-slug.php on line 38

I have not edited the plugin.
In addition, I would like to know why

defined( 'ABSPATH' ) || exit;

Sincerely yours

**Comment by chesio** [comment]
Hi,

it seems like the file `includes/classes/class-ba-edit-author-slug.php` is missing on your WordPress installation - maybe plugin installation broke in the middle of process?

As for `defined( 'ABSPATH' ) || exit;` bit - this is a de facto standard way how to prevent direct access to PHP files that should be only included/required from other files.

Cheers,
Česlav

**Comment by speedysense** [comment]
I suggest to do this things without plugin checkout this [article](https://speedysense.com/change-author-url-slug-without-plugin/) may be help you. 

Cheers
