### ISSUE TITLE
Remove the call to add_options_page completely via role

### ISSUE THREAD

**Issue by sidouglas** [thebrandonallen/edit-author-slug#21]
on your add_options_page call in `admin.php` you hard code the edit_users capability to render the plugin. 
Despite hooking the ba_eas_can_edit_author_slug to prevent the actual update of settings, it would be nice to just hide the page altogether for users that don't have the permission.

```
function ba_eas_add_settings_menu() {
	add_options_page(
		__( 'Edit Author Slug Settings', 'edit-author-slug' ),
		__( 'Edit Author Slug', 'edit-author-slug' ),
    apply_filters('ba_eas_add_settings_menu', 'edit_users'),
    'edit-author-slug',
		'ba_eas_settings_page_html'
	);
}
```

**Comment by sidouglas** [comment]
Thank you! 👍

**Comment by thebrandonallen** [comment]
No problem. Thanks for catching and reporting that!
